name: Run Feature Tests

on:
  push:
    branches:
      - 'feature/**'  # Trigger on any feature branch

jobs:
  test-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run relevant test for feature branch
        run: |
          echo "Branch: ${{ github.ref_name }}"
          # Extract feature name from branch (remove 'feature/' prefix)
          feature_name="${{ github.ref_name }}"
          feature_name="${feature_name#feature/}"
          test_file="tests/test_${feature_name}.py"

          if [ -f "$test_file" ]; then
            echo "✅ Running test: $test_file"
            pytest "$test_file"
          else
            echo "⚠️ Test file not found for branch: $feature_name"
            exit 1
          fi